# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: email

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_USER: IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: ROLE_MODERATOR

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            pattern: ^/

            provider: our_db_provider

            form_login:
                login_path: /login
                check_path: /login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: todo

            logout:
                path: /logout
                target: /

#        login_firewall:
#            pattern:   ^/login$
#            anonymous: ~
#        secured_area:
#            pattern:    ^/
#            form_login: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/todo, roles: ROLE_USER}
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
#    access_control:
#        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: /register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: /, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: /forgot-password, roles: ROLE_USER }
#        - { path: ^/product, roles: ROLE_USER }
#        - { path: ^/edit-product, roles: ROLE_MODERATOR }
#        - { path: ^/edit-category, roles: ROLE_MODERATOR }
#        - { path: ^/edit-user, roles: ROLE_ADMIN }
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/, roles: ROLE_ADMIN }
